### ISSUE TITLE
DREME call error with e-value 0

### ISSUE THREAD

**Issue by michauhl** [cinquin/MEME#1]
Hello, 
I'm getting a non-informative error when calling DREME with -e 0. Might be good to add a parameter check for this, to get a meaningful error message. 

```
$ dreme -oc dreme_out -rna -norc -p dreme_test_sites.fa -e 0               

Reading positive sequences dreme_test_sites.fa ...
Shuffling positive sequences...
Looking for motif 1...
Counting positive sequences with each word...
Counting negative sequences with each word...
Applying Fisher's Exact Test to 45630 words...
Generalizing top 100 of 45630 REs to 1 ambiguous characters...
Generalizing top 100 of 172 REs to 2 ambiguous characters...
Generalizing top 24 of 24 REs to 3 ambiguous characters...
Generalizing top 1 of 1 REs to 4 ambiguous characters...
Computing exact p-values for 100 REs...
Traceback (most recent call last):
  File "/home/uhlm/meme/bin/dreme", line 1900, in <module>
    if __name__ == '__main__': main()
  File "/home/uhlm/meme/bin/dreme", line 1849, in main
    alph, given_only)
  File "/home/uhlm/meme/bin/dreme", line 1163, in find_print
    minw, maxw, ethresh, log_add_pthresh, alph, given_only)
  File "/home/uhlm/meme/bin/dreme", line 299, in output_best_re
    if best_log_Evalue <= log(ethresh):
ValueError: math domain error
```

**Comment by cinquin** [comment]
Hi,
This isn't the official repository for MEME. Since this issue is not related to the couple tweaks I made to the code I suggest you get in touch with the authors. Alternatively, if you have a patch and want to make a pull request I'd be happy to merge it.

**Comment by michauhl** [comment]
Hi, sure if I can help, but don't know what is the official one ? I couldn't find it. Are you in contact with the authors / how do you make sure the bug fixes go in the official version?

**Comment by cinquin** [comment]
You'll find the source at http://meme-suite.org/doc/download.html
As indicated in the message of the first commit, this repository is based on the same version as is currently available at that link.
